slogan: "experience is what you get when you were expecting something else"

show_heart: true

show_slogan: true

menu:
  - title: Categories
    url: categories
    intro: "All the categories."
    # icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    # icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    # icon: "fa fa-user"
  - title: Projects
    url: projects
    intro: "Things I built."
  - title: RSS
    url: atom.xml
    intro: "Subscribe me."
    # icon: "fa fa-user"
  - title: Archives
    url: archives
    intro: "All the articles."
    # icon: "fa fa-archive"

links:
  - title: "about me"
    url: "https://trog.codes/about"
    intro: "who is this guy"
    icon: "fa fa-user"
  
  - title: github
    url: https://github.com/rconjoe
    intro: "my personal github"
    icon: "fa fa-github"

  # - title: twitch 
  #   url: https://twitch.tv/rconjoe
  #   intro: "i stream random things here"
  #   icon: "fa fa-twitch"
  #
  - title: steam
    url: https://steamcommunity.com/id/rconjoe
    intro: "my steam"
    icon: "fa fa-steam"

  # - title: youtube
  #   url: https://youtube.com/@trogdooor
  #   intro: "my youtube"
  #   icon: "fa fa-youtube"
  #
  # - title: ig
  #   url: https://www.instagram.com/trogdooor
  #   intro: "me!"
  #   icon: "fa fa-instagram"
  #
  - title: spotify
    url: https://open.spotify.com/user/aq8x36wy57u76p4i2mpnp6k7m?si=1cf1b8d5a0364082
    intro: "my incredible taste in music"
    icon: "fa fa-spotify"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: atom.xml
fancybox: true
favicon: favicon.png
#duoshuo_shortname: 


# Analytics
google_analytics:
  enable: false 
  siteid: ''


# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR

#valine
valine: 
  enable: false
  appId: 'xxx'
  appKey: 'xxx'
  placeholder: ""
  visitor: false
  avatar: 'monsterid'
  requiredFields: ['nick','mail']
  pageView: false
  
#waline
waline:
  enable: false
  serverURL: ''
  pageview: false
  lang: en
  dark: true
  requiredMeta: ['nick', 'mail']
  locale:
    placeholder: 'Comment with Email address will get notification when replied'

gitalk:
  enable: false
  clientID: ''
  clientSecret: ''
  repo: ''
  owner: ''
  admin: ['']
  id: location.pathname
  distractionFreeMode: true
